# Render Deployment Configuration
# This file is not needed for Render - keeping for reference
# Render automatically detects Node.js apps and builds them

[build]
  # Render uses different configuration
  # Build settings are configured in Render dashboard
  base = "."
  publish = "client/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
